### ISSUE TITLE
Not clear on the arguments of dynFitness

### ISSUE THREAD

**Issue by AARoble** [btglau/matlab_dynamics#1]
Hi, just wondering if you could help: what form does the param argument of dynFitness function takes? I looked in the input_example folder, but neither of the two files contain some sort of struct, which is what I concluded param to be, looking at lines such as param.elecKE = param.elecKE/param.Eh and so on...

Many thanks!

**Comment by btglau** [comment]
Hi there! You can find the input parsing functions in dynOpt_input.m and mcInput.m. When you call dynOpt_func.m from command line, all the arguments are passed as strings, and a piece of code converts the numeric ones to a number format so that matlab's argparse recognizes it. The varargin is then dispatched to the appropriate input function to be parsed into parameter-value arguments held in the param structure.

**Comment by AARoble** [comment]
Ok.. I will look at it again now. A few days ago, I thought I saw here another reply where you showed an example input file, how to call the relevant functions and the results you obtained. I saw it and was planning on looking at it properly this weekend. Unfortunately it is gone now..

**Comment by btglau** [comment]
I don't recall making such an example, but I could put one up this week once I have time.

**Comment by btglau** [comment]
Hello,

I've updated the README with more concrete instructions on how to run the program.

**Comment by AARoble** [comment]
Thanks!
